name: Test Execution
on: 
    workflow_dispatch:

jons:
    build:
        name: test-execution
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout the repository source code
              uses: actions/checkout@v4
            
            - name: Install Dependencies
              run: pip install selenium pytest
            
            - name: Run Test
              run: pytest
