name: Test Execution
on: 
    workflow_dispatch:

jobs:
    build:
        name: test-execution
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout the repository source code
              uses: actions/checkout@v4
            
            - name: Install Dependencies
              run: pip install -r requirements.txt --upgrade
            
            - name: Run Test
              run: pytest --html=test-results/report.html
            
            - name: Upload HTML Report
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                 name: test-results
                 path: test-results
